image: python:3.10

stages:
  - test

variables:
  # Use a specific version of ChromeDriver to avoid compatibility issues.
  CHROME_DRIVER_VERSION: "114.0.5735.90" # Replace with the desired version
  # Path where the chromedriver will be installed
  CHROMEDRIVER_PATH: /usr/local/bin/chromedriver

before_script:
  - apt-get update -yq
  - apt-get install -yq wget unzip xvfb libgconf-2-4
  # Install Google Chrome
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - apt-get update -yq
  - apt-get install -yq google-chrome-stable
  # Download and install ChromeDriver
  - wget "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - mv chromedriver $CHROMEDRIVER_PATH
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - export DISPLAY=:99
    - Xvfb :99 -screen 0 1024x768x24 &
    - python -m unittest discover -s tests -p "test_*.py"
  artifacts:
    when: always
    reports:
      junit: junit.xml # Optional: to generate JUnit reports

# Example of a more robust way to handle the chromedriver download
# This uses a more specific URL and handles errors better.
# before_script:
#   - apt-get update -yq
#   - apt-get install -yq wget unzip xvfb libgconf-2-4
#   - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#   - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#   - apt-get update -yq
#   - apt-get install -yq google-chrome-stable
#   - CHROME_DRIVER_URL=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_DRIVER_VERSION:0:3}" | tr -d '\n')
#   - wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_URL}/chromedriver_linux64.zip" || exit 1
#   - unzip /tmp/chromedriver.zip -d /tmp/
#   - chmod +x /tmp/chromedriver
#   - mv /tmp/chromedriver $CHROMEDRIVER_PATH
#   - pip install -r requirements.txt
