name: Selenium Tests with pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Adjust as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest selenium  # Install pytest and Selenium

      - name: Install Chrome Driver  # Assuming you want to use Chrome
        run: |
          wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set Chrome binary path
        run: |
          mkdir -p /opt/google/chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo mkdir /etc/sources.list.d
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/sources.list.d/google.list
          rm google-chrome-stable_current_amd64.deb
          sudo apt-get install -y --fix-broken
          sudo apt-get install -y xvfb

      - name: Run Selenium tests (Headless mode)
        run: |
          pytest --headless testCases  # Assuming your test files are in testCases directory


