name: Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11]
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest selenium webdriver-manager
      - name: Setup Chrome (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          chromium-browser --version
      - name: Setup Chrome Driver (Linux)
        if: runner.os == 'Linux'
        run: |
          export CHROME_BIN=/usr/bin/chromium-browser
          export DISPLAY=:99
          sudo Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Run tests
        env:
          PYTHONUNBUFFERED: 1
        run: |
          pytest --headless


        
