name: Login
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest selenium webdriver-manager
          sudo apt-get update
          sudo apt-get install -y libnss3 libgdk-pixbuf2.0-0 libatk-bridge2.0-0 libatk1.0-0 libcups2

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run tests
        run: |
          mkdir -p testCases/reports
          pytest testCases/test_login_page.py --browser=chrome --html=testCases/reports/reports.html

      - name: Set output
        id: results
        run: echo "artifactPath=testCases/reports/" >> $GITHUB_OUTPUT

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ${{ steps.results.outputs.artifactPath }}



        
